App\Entity\Gossip:
  type: entity
  table: gossips
  repositoryClass: App\Repository\Gossip\Repository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    text:
      type: text
