App\Entity\OrderAddress:
  type: entity
  table: order_addresses
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    street:
      type: string
    zip:
      type: string
      nullable: true
