App\Entity\Product:
  type: entity
  table: products
  repositoryClass: App\Repository\ProductRepository
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
    imageUrl:
      type: string
    price:
      type: decimal
      precision: 10
      scale: 2
